### ISSUE TITLE
Add GitHub CI for Window and Linux replacing Travis

### ISSUE THREAD

**Issue by kraigher** [kraigher/rust_hdl#47]
- Replace Travis with GitHub CI.
- Run unit tests on Linux & Windows.

**Comment by Xcodo** [comment]
I did a super-simple GitHub Actions cross compilation task [on my fork](https://github.com/Xcodo/rust_hdl/blob/master/.github/workflows/build-test-all.yml). Seems to work.

I can add a pull request if you want to start from there? Or do you want to mirror the more complex Travis setup you have first?

**Comment by kraigher** [comment]
Yeah we can add it now and remove travis later when github ci makes it redundant

**Comment by Bochlin** [comment]
@Xcodo Wouldn't it make sense to compile and run tests for windows on windows?

**Comment by Xcodo** [comment]
Yes it probably would. I started using cross on Travis using `cross` then transferred my config over without looking at the runners hard. I've seen your VSCode setup and was going to go back and look at doing it on Windows. I would also use the maintained cargo actions rather than shelling commands to cargo

**Comment by Xcodo** [comment]
Too many ideas, not enough time in front of a PC at the moment!

**Comment by kraigher** [comment]
The only thing travis does that the github workflow doesn't is to publish to crates.io and build and publish the docker image.

**Comment by Xcodo** [comment]
Both of those will need the keys added to the project secrets store.
