### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by m-kru** [kraigher/rust_hdl#82]
@kraigher I wanted to ask one question, as you have probably already considered this issue. Have you thought about structuring project in the same way the standard is structured.
![image](https://user-images.githubusercontent.com/26227737/86046045-d316f780-ba4c-11ea-90a1-41cb272073f9.png)
For example each section would be a module, and subsection would be represented by structs, enums, traits, etc.
At first it looks like a great idea, but maybe there is something that I have overlooked.
I would really appreciate you experience as you have probably tackled a lot of problems during implementation.

**Comment by kraigher** [comment]
It is subjective but I do not think it is a good idea to structure all code around the standard. The standard is in my opinion not written with an eye towards implementation. In my experience there are a lot of ambiguities. I think it is a result of the standard being very superficially focused without any opinion or hint at all about the data model of an implementation. Since it is superficial the chapter structure fits well with parsing and ast definition but less so with later stages such as semantic analysis.
